spring:
  application:
    name: url-shortener-sb
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}
  jpa:
    hibernate:
      ddl-auto: update
  #    show-sql: true
  main:
    banner-mode: off
jwt:
  secret: ${JWT_SECRET}
  expiration: 600000
frontEnd:
  url: ${FRONTEND_URL}
#logging:
#  level:
#    root: ERROR